version: '3.8'

services:
  api:
    build: .
    container_name: warehouse-api
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
    restart: always
    networks:
      - app_network

  db:
    image: postgres:14
    container_name: warehouse-db
    ports:
      - "5432:5432" 
    env_file:
      - .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  migrations:
    build: .
    container_name: warehouse-migrations
    env_file:
      - .env
    volumes:
      - ./alembic:/app/alembic
    depends_on:
      db:
        condition: service_healthy
    command: alembic upgrade head
    networks:
      - app_network


volumes:
  pg_data:

networks:
  app_network:
    driver: bridge